# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'mont(gomery), chr(is)'
tagline:          'A website for Chris Montgomery'
description:      'Chris Montgomery is a web developer. He works for a website called Billy Penn.'
url:              http://montchr.io
baseurl:          /

paginate:         5


# Custom vars
# ==============================================================================

author:
  name:           'Chris Montgomery'
  url:            https://twitter.com/montchr
  twitter:        https://twitter.com/montchr
  github:         https://github.com/montchr
  linkedin:       https://www.linkedin.com/in/montchr
  pinboard:       https://pinboard.in/u:montchr
  ello:           https://ello.co/montchr
