# Permalinks
permalink:        pretty

# Setup
title:            'montgomery, chris'
tagline:          'A website for Chris Montgomery'
description:      'nil'
url:              https://montchr.io

paginate:         5

gems: ['jekyll-github-metadata']
livereload: true


# Custom vars
# ==============================================================================

author:
  name:           'Chris Montgomery'
  url:            https://twitter.com/montchr
  github:         https://github.com/montchr
  twitter:        https://twitter.com/montchr
  pinboard:       https://pinboard.in/u:montchr
  linkedin:       https://www.linkedin.com/in/montchr
