# Permalinks
permalink:        pretty

# Setup
title:            'mont(gomery), chr(is)'
tagline:          'A website for Chris Montgomery'
description:      'Chris Montgomery is a web developer. Chris works for a company called Spirited Media.'
url:              http://montchr.io

paginate:         5

gems: ['jekyll-github-metadata']
livereload: true


# Custom vars
# ==============================================================================

author:
  name:           'Chris Montgomery'
  url:            https://twitter.com/montchr
  github:         https://github.com/montchr
  twitter:        https://twitter.com/montchr
  pinboard:       https://pinboard.in/u:montchr
  linkedin:       https://www.linkedin.com/in/montchr
